ln -sv ~/dotfiles/.vimrc ~
ln -sv ~/dotfiles/.bashrc ~
ln -sv ~/dotfiles/fish ~/.config/
ln -sv ~/dotfiles/ranger ~/.config/
ln -sv ~/dotfiles/nvim ~/.config/
ln -sv ~/dotfiles/.gitconfig ~
ln -sv ~/dotfiles/.tmux.conf ~
ln -sv ~/dotfiles/.i3 ~
ln -sv ~/dotfiles/.i3status.conf ~
ln -sv ~/dotfiles/.latexmkrc ~
ln -sv ~/dotfiles/ftplugin ~/.vim/
ln -sv ~/dotfiles/.Xmodmap ~
